### ISSUE TITLE
在 HOME 環境變數未設定的情況下 ucimf 會 crash（orig.: 以 root 身份取代 getty 執行 fbterm 時無法啟用輸入法）

### ISSUE THREAD

**Issue by Vdragon** [matlinuxer2/ucimf#91]
最近參考了 [terminal - How do I make Ubuntu start fbterm in the tty on startup? - Super User](http://superuser.com/questions/438950/how-do-i-make-ubuntu-start-fbterm-in-the-tty-on-startup) 的作法用 fbterm 取代 TTY1 的 getty，但是發現沒辦法正常啟用輸入法的問題（於一般使用者下執行正常）

### 套用的修正
* [Vubuntu/Patches/語言設定(Locale settings)/TTY 終端機中文支援/修正「安裝了 ucimf-chewing 但是新酷音輸入法還是叫不出來」的問題 at master · Vdragon/Vubuntu](https://github.com/Vdragon/Vubuntu/tree/master/Patches/%E8%AA%9E%E8%A8%80%E8%A8%AD%E5%AE%9A(Locale%20settings)/TTY%20%E7%B5%82%E7%AB%AF%E6%A9%9F%E4%B8%AD%E6%96%87%E6%94%AF%E6%8F%B4/%E4%BF%AE%E6%AD%A3%E3%80%8C%E5%AE%89%E8%A3%9D%E4%BA%86%20ucimf-chewing%20%E4%BD%86%E6%98%AF%E6%96%B0%E9%85%B7%E9%9F%B3%E8%BC%B8%E5%85%A5%E6%B3%95%E9%82%84%E6%98%AF%E5%8F%AB%E4%B8%8D%E5%87%BA%E4%BE%86%E3%80%8D%E7%9A%84%E5%95%8F%E9%A1%8C)
* [Vubuntu/Patches/語言設定(Locale settings)/TTY 終端機中文支援/將 TTY1 的 getty 改為 fbterm at master · Vdragon/Vubuntu](https://github.com/Vdragon/Vubuntu/tree/master/Patches/%E8%AA%9E%E8%A8%80%E8%A8%AD%E5%AE%9A(Locale%20settings)/TTY%20%E7%B5%82%E7%AB%AF%E6%A9%9F%E4%B8%AD%E6%96%87%E6%94%AF%E6%8F%B4/%E5%B0%87%20TTY1%20%E7%9A%84%20getty%20%E6%94%B9%E7%82%BA%20fbterm)

### Stacktrace
![_447](https://cloud.githubusercontent.com/assets/1192163/6888253/c777c804-d6aa-11e4-9276-4429f04e8d3c.png)

### 作業系統
Ubuntu GNU/Linux 14.04 x86 32bit

### ucimf 軟體來源
Ubuntu 14.04 archive

### 軟體版本
* ucimf
    * 2.3.8
* ucimf-chewing
    * 0.3
* fbterm-ucimf
    * 0.2.9

**Comment by matlinuxer2** [comment]
收到。 謝謝你的 feedback~

從 backtrace 的內容來看，猜測應該是在 src/options.cpp 的 Options::Options() 裡面中斷的. 

想進一步詢問一下幾個地方:
1. /root/.ucimf.conf 跟 /etc/ucimf.conf 是否存在 & 可正常讀寫?
2. 承1. ucimf.conf 的設定檔內容為何?
3. $HOME/.ucimf-log 是否存在 ( 若有的話，希望有 attachment 可進一步分析 )

thanks~

**Comment by Vdragon** [comment]
> \1. /root/.ucimf.conf 跟 /etc/ucimf.conf 是否存在 & 可正常讀寫?

```
Vdragon % ls -l /etc/ucimf.conf
-rw-r--r-- 1 root root 338 12月 30  2013 /etc/ucimf.conf
Vdragon % sudo ls -l /root/.ucimf.conf
[sudo] password for Vdragon: 
ls: 無法存取 /root/.ucimf.conf: 沒有此一檔案或目錄
Vdragon % ls -l ~/.ucimf.conf
ls: 無法存取 /home/Vdragon/.ucimf.conf: 沒有此一檔案或目錄
```

> \2. 承1. ucimf.conf 的設定檔內容為何?

```
Vdragon % pastebinit /etc/ucimf.conf 
http://paste.ubuntu.com/10707297/
```

> \3. $HOME/.ucimf-log 是否存在 ( 若有的話，希望有 attachment 可進一步分析 )

```
Vdragon % ls -l ~/.ucimf-log
-rw------- 1 Vdragon Vdragon 171  3月 30 06:27 /home/Vdragon/.ucimf-log
Vdragon % pastebinit ~/.ucimf-log
http://paste.ubuntu.com/10707284/
Vdragon % sudo ls -l /root/.ucimf-log
ls: 無法存取 /root/.ucimf-log: 沒有此一檔案或目錄
```

**Comment by Vdragon** [comment]
按下 Ctrl + Space 時會噴出
```
terminate called after throwing on instance of 'std::logic_error'
what():  basic_string::_s_construct null not valid
```

另外在 fbterm 不設成 tty 的時候以 root 身份手動執行是可以正常使用輸入法的

**Comment by matlinuxer2** [comment]
> 另外在 fbterm 不設成 tty 的時候以 root 身份手動執行是可以正常使用輸入法的

這個線索很關鍵!! thanks~
從這一點來看，應該是 tty 啟動的方式，比一般方式啟動，少了什麼設定。

目前猜測可能是 Options::Options() 中，在抓取 $HOME 的環境參數並新建一個 c++ string 時，出現的 runtime error. 

```
src/options.cpp:

 45 Options::Options()
 46 {
 47   string conf = getenv("HOME");
 48   conf += "/.ucimf.conf";
 49 
```
不知道 tty 啟動的設定中，有沒有什麼方式可以餵入 HOME="/root" 之類的環境參數?

**Comment by buganini** [comment]
用ENV(1)塞?

**Comment by Vdragon** [comment]
@buganini 用 env(1) 可以！感謝！

也許應該要修正環境變數無效就會 crash 的問題？
